"""add geo and device columns to clicks

Revision ID: 65e1e1fea992
Revises: e685059d9951
Create Date: 2026-08-09 01:51:45.023446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65e1e1fea992'
down_revision: Union[str, Sequence[str], None] = 'e685059d9951'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clicks', sa.Column('ip_address', sa.String(length=45), nullable=True))
    op.add_column('clicks', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('clicks', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('clicks', sa.Column('device_type', sa.String(length=20), nullable=True))
    op.add_column('clicks', sa.Column('browser', sa.String(length=50), nullable=True))
    op.add_column('clicks', sa.Column('os', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clicks', 'os')
    op.drop_column('clicks', 'browser')
    op.drop_column('clicks', 'device_type')
    op.drop_column('clicks', 'city')
    op.drop_column('clicks', 'country')
    op.drop_column('clicks', 'ip_address')
    # ### end Alembic commands ###
